### PR TITLE
Fixes for undefined behavior caused by dangling pointers

### LINKED ISSUE #37: Potential dangling pointers from caching behavior
Commit https://github.com/DoubleDeez/MDFastBinding/commit/3162484e645ae6a0048c06c7c4e68446543d5b3f added some logic to cache various pointers and minimize redundant logic, however there are multiple cases where the cached pointers can dangle and result in undefined behavior. Here are two scenarios where this has happened:

**Steps to reproduce:**

Scenario 1:
1. Follow the repro steps outlined in issue #22 
2. Observe that after performing step 7, the application crashes (this may or may not happen since there is undefined behavior)
-- In our case we crashed within `FMDFastBindingPropertySetter_Objects::CanSetProperty`

**Workaround**: Comment out the following line within `FMDFastBindingFunctionWrapper::GetParams()`:

```
if (!LastFrameFunctionUpdated.IsSet() || LastFrameFunctionUpdated.GetValue() != GFrameCounter)
```

Scenario 2:
1. Enable diffing for binding graphs
2. Open a widget blueprint asset that contains existing bindings
3. Compile the blueprint
4. Observe that it crashes (this may or may not happen since there is undefined behavior)
-- In our case we crashed within `UMDFastBindingGraphNode::AllocateDefaultPins`

**Workaround**: Comment out the following line within `FMDFastBindingFieldPath::GetFieldPath()`:

```
if (!LastFrameUpdatedPath.IsSet() || LastFrameUpdatedPath.GetValue() != GFrameCounter)
```

### PR DESCRIPTION
**Pull request by jdaignault**
We currently have a bunch of undefined behavior stemming from unmanaged `FProperty*` pointers going stale and left in a dangling state. This behavior would generally occur during contexts that triggered a blueprint reload/recompilation, such as:

- Compiling a widget blueprint with bindings
- Duplicating an existing widget blueprint asset with bindings
- Opening the blueprint diff tool on a widget blueprint with bindings

These changes primarily update a bunch of the plugin code to rely more on `TWeakFieldPtr<>` for stability, along with introducing various other fixes to mitigate the regressions that arose from that change (instead of invoking undefined behavior).

Fixes #37

### CODE REVIEW

File: Source/MDFastBindingBlueprint/Private/BlueprintExtension/MDFastBindingWidgetBlueprintExtension.cpp [hunk 1]
```diff
@@ -77,6 +64,9 @@ void UMDFastBindingWidgetBlueprintExtension::HandleCopyTermDefaultsToDefaultObje
 		
 			// There's a chance we could perform some compile-time steps here that would improve runtime performance
 			CompilerContext->AddExtension(WidgetBPClass, BindingClass);
+
+			// The blueprint has been fully recompiled here, we need to update the binding graphs
```
Comment (DoubleDeez) [inline Source/MDFastBindingBlueprint/Private/BlueprintExtension/MDFastBindingWidgetBlueprintExtension.cpp:68]: So does that mean that the diff tool compiles both versions of the blueprints being compared? That's surprising.

File: Source/MDFastBindingBlueprint/Private/BlueprintExtension/MDFastBindingWidgetBlueprintExtension.cpp [hunk 2]
```diff
@@ -101,7 +91,36 @@ void UMDFastBindingWidgetBlueprintExtension::HandleEndCompilation()
...
+			{
+				RefreshPinnedGraphs();
+			}
+		}
+
+		CompilerContext = nullptr;
+	}
+}
+
+void UMDFastBindingWidgetBlueprintExtension::RefreshPinnedGraphs()
```
Comment (DoubleDeez) [inline Source/MDFastBindingBlueprint/Private/BlueprintExtension/MDFastBindingWidgetBlueprintExtension.cpp:110]: The "Refresh" naming is a bit misleading since it only populates the Pinned Graphs for the first time it's called

Comment (jdaignault) [reply Source/MDFastBindingBlueprint/Private/BlueprintExtension/MDFastBindingWidgetBlueprintExtension.cpp:110]: That makes sense, I'll change it to `PopulatePinnedGraphs`

File: Source/MDFastBinding/Private/MDFastBindingFunctionWrapper.cpp [hunk 3]
```diff
@@ -35,18 +37,18 @@ UClass* FMDFastBindingFunctionWrapper::GetFunctionOwnerClass() const
 	return OwnerClassGetter.IsBound() ? OwnerClassGetter.Execute() : nullptr;
 }
 
-const TArray<const FProperty*>& FMDFastBindingFunctionWrapper::GetParams()
+TArray<const FProperty*> FMDFastBindingFunctionWrapper::GetParams()
 {
 #if WITH_EDITORONLY_DATA
-	if (!LastFrameFunctionUpdated.IsSet() || LastFrameFunctionUpdated.GetValue() != GFrameCounter)
+	if (!LastFrameFunctionUpdated.IsSet() || LastFrameFunctionUpdated.GetValue() != GFrameCounter || FunctionMember.ResolveMember<UFunction>() != FunctionPtr)
```
Comment (DoubleDeez) [inline Source/MDFastBinding/Private/MDFastBindingFunctionWrapper.cpp:43]: Is this extra condition not needed in the other functions? (GetFunctionPtr, CallFunction)

Comment (jdaignault) [reply Source/MDFastBinding/Private/MDFastBindingFunctionWrapper.cpp:43]: The main offender was `GetParams` as it was the only one being called during `SetupBindingItems`, but I see no harm in adding this check for the other functions if you feel it would make things more robust.

Comment (DoubleDeez) [reply Source/MDFastBinding/Private/MDFastBindingFunctionWrapper.cpp:43]: Feel like we might as well have it consistent throughout

Comment (jdaignault) [reply Source/MDFastBinding/Private/MDFastBindingFunctionWrapper.cpp]: Resolved in commit [927b7bc](https://github.com/DoubleDeez/MDFastBinding/pull/40/commits/927b7bc99fbcb2df4c1c3398a0b947737532edc0)

File: Source/MDFastBindingBlueprint/Private/BlueprintExtension/MDFastBindingWidgetBlueprintExtension.cpp (hunk 2 above)
Comment (jdaignault) [reply Source/MDFastBindingBlueprint/Private/BlueprintExtension/MDFastBindingWidgetBlueprintExtension.cpp]: Resolved in commit [5559d6b](https://github.com/DoubleDeez/MDFastBinding/pull/40/commits/5559d6b4a030188164ffc031f228b2c46064e36b)

**Comment by DoubleDeez** [comment]
Changed how `FMDFastBindingFieldPathVariant` works a bit (and renamed it to FMDFastBindingWeakFieldVariant) and merged, let me know if you think that should change.

Thanks for digging into the issue, I didn't have diffs enabled here which I think was the root of the issues.
